services:
  # 🔹 Banco de Dados PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: prime
      POSTGRES_PASSWORD: prime
      POSTGRES_DB: order_system
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prime -d order_system"]
      interval: 10s
      retries: 5

  # 🔹 Backend Express (Notificações)
  notification_api:
    build:
      context: ./OrderSystem.API/OrderSystem.Notification.API
      dockerfile: Dockerfile
    container_name: notification_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres_db:5432/mydatabase"

  # 🔹 Backend C# (Pedidos) + Migrations
  order_api:
    build:
      context: ./OrderSystem.API/OrderSystem.Order.API
      dockerfile: Dockerfile
    container_name: order_api
    restart: always
    ports:
      - "5001:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres_db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword"

  # 🔹 Backend Python (Pagamentos)
  payment_api:
    build:
      context: ./OrderSystem.API/OrderSystem.Payment.API
      dockerfile: Dockerfile
    container_name: payment_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres_db:5432/mydatabase"

  # 🔹 Frontend React
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - order_api
      - notification_api
      - payment_api
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:
